### PR TITLE
Removed unnecessary blank lines and corrected indentation in multiple…

### PR DESCRIPTION
**Pull request by Beckyowino**
Screenshots of the site
Screenshot from 2024-11-25 10-32-48
Screenshot from 2024-11-25 10-32-09
Screenshot from 2024-11-25 10-31-55
Screenshot from 2024-11-25 10-31-17
Screenshot from 2024-11-25 10-30-59
Screenshot from 2024-11-25 10-30-45
Screenshot from 2024-11-25 10-30-36
Screenshot from 2024-11-25 10-30-24
Screenshot from 2024-11-25 10-29-58
Screenshot from 2024-11-25 10-29-50
Screenshot from 2024-11-25 10-29-38
Screenshot from 2024-11-25 10-29-28
Screenshot from 2024-11-25 10-29-20
Screenshot from 2024-11-25 10-29-06

### CODE REVIEW

**Comment by EricOuma** [comment]
Looking Good

**Comment by EricOuma** [comment]
Is the slider working?

**Comment by Beckyowino** [comment]
> Is the slider working?

Yes

**Comment by EricOuma** [comment]
Okay. I hope you understand how it's working.

**Comment by Beckyowino** [comment]
> Okay. I hope you understand how it's working.

Yes

**Pull request merged**
