### PR TITLE
Function/authorpage

### PR DESCRIPTION
**Pull request by Beckyowino**
Started working on the authors page and ade minor changes on pricing page.

### CODE REVIEW

**Comment by EricOuma** [comment]
Share a screenshot of the page

**Comment by Beckyowino** [comment]
screenshots of pricing and authors

**Comment by EricOuma** [comment]
Where is the screenshot? Also, your PR has conflicts. Do some research on how to resolve PR conflicts.

**Comment by EricOuma** [comment]
Attach image(s) of the screenshot(s) to a comment

**Comment by Beckyowino** [comment]
> Share a screenshot of the page

**Comment by Beckyowino** [comment]
Screenshot from 2024-11-13 20-25-50
Screenshot from 2024-11-13 20-25-29
Screenshot from 2024-11-13 20-25-16
Screenshot from 2024-11-13 20-24-31
Screenshot from 2024-11-13 20-24-14

**Pull request merged**
